# Generated by Django 5.1.5 on 2025-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('main_picture', models.ImageField(upload_to='uploads/%Y/%m/%d')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
